config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'
  devise_for :users
  resources :users do
    member do
      get 'followers'
      get 'followings'
    end
    resource :relationships, only: [:create, :destroy]
  end 
    resources :homes
  get "home/about" => 'homes#about'
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,:registerable,:recoverable, :rememberable, :validatable
         has_many :books, dependent: :destroy
         has_many :book_comments, dependent: :destroy
         has_many :favorites, dependent: :destroy
         attachment :profile_image
      validates :name, presence: true, length: {minimum: 2, maximum: 20}
      validates :introduction, length: {maximum: 50}
        # フォローしている側
          has_many :relationships, class_name: 'Relationship', foreign_key: 'following_id'
          has_many :followings, through: :relationships, source: :followed

        # フォローされている側
          has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id'
          has_many :followers, through: :reverse_of_relationships, source: :following


          # フォローするメソッド
          def follow(user)
            unless self == user
              # 見つかれば見つけて返してなければ作成→二重フォローを防ぐ
              relationships.find_or_create_by(followed_id: user.id)
            end
          end

          # フォローを外す
          def unfollow(user)
            relationship = relationships.find_by(followed_id: user.id)
            relationship.destroy if relationship
          end

          # フォローしているか確認
          def follow?(user)
            followings.include?(user)
          end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  def index
    if user_signed_in?
    #form_withに必要な記述
    @book = Book.new
    #ログイン中のユーザーのデータを取り出している
    @user = User.find(current_user.id)
    #全ユーザーのデータを取り出している
    @users = User.all
    else
       redirect_to new_user_registration_path
    end
  end

  #viewを持たないからインスタンス変数がいらない
  def create
   #form_withに必要な記述
   book = Book.new(book_params)
   #booksモデルのuser_idカラムにログイン中のidを入れる
   book.user_id = current_user.id
   #内容を保存する
   if book.save
      flash[:success] = 'Book was successfully created.'
      #bookの詳細画面へ遷移（ここに遷移するidを指定する)
      redirect_to book_path(book.id)
   else
     render :index
   end
    #bookの詳細画面へ遷移（ここに遷移するidを指定する)
   redirect_to book_path(book.id)
  end



  def show
    if user_signed_in?
     #form_withに必要な記述
    @book = Book.new
    #ログイン中のユーザーidとBookモデルのuser_idが一致するものすべてをユーザーが投稿したものを表示するために取得している
    @books = Book.where(user_id: current_user.id)
    #そのユーザーのデータを取得
    @user = User.find(params[:id])
    else
       redirect_to new_user_registration_path
    end

  end

  def edit
    
     #新規投稿ではなく編集なので編集したいidを取ってきてform_withに渡している
     @user = User.find(params[:id])
    if   @user.id == current_user.id
     render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
     #bookのidを取り出している
    @user = User.find(params[:id])
    #データを受け取るbook_paramsに更新している
   if @user.update(user_params)
    #Bookの詳細画面に遷移
     flash[:success] = 'User info was successfully Updated.'
      redirect_to user_path(@user.id)
   else
      render :edit
   end
  end

  private

  def user_params
  params.require(:user).permit(:profile_image, :name, :introduction)
  end
  def book_params
  params.require(:book).permit( :title, :body, :id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
 <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message) %>
 <% end %>
<h3>User info</h3>


<%= attachment_image_tag user, :profile_image, fallback: "no-image.png" ,class:"profile-image" %>

<p>name: <%= user.name %></p>
<p>introduction: <%= user.introduction %></p>
<p>followings:<%= link_to user.followings.count, followings_user_path(user)%></p>
<p>followers:<%= link_to user.followers.count, followers_user_path(user)%></p>
<div class="row"><%= link_to "編集", edit_user_path(user.id), class: "col-xs-7 btn btn-default glyphicon glyphicon-wrench edit_user_27716" %></div>
<div class="row", style="margin-top: 10px;">
 <%if current_user.follow?(user)%>
    <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class:"btn btn-sm btn-success col-xs-7" %>
 <%elsif current_user == user%>
 <%else%>
    <%= link_to "フォローする", user_relationships_path(user), method: :post, class:"btn btn-sm btn-success col-xs-7" %>
 <%end%>
</div>



<%= form_with model:book, local:true do |f| %>
<h3>New book</h3>
 <div class = "field row">
  <h4>Title</h4>
  <%= f.text_field :title %>
</div>


<div class = "field row">
  <h4>Opinion</h4>
  <%= f.text_area :body %>
</div>


<div class = "actions row">
<%= f.submit 'Create Book' %>
</div>


<% end %>

app/views/users/_temp.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, size: "40x40", fallback: "no-image.png") %></td>
        <td><%= user.name %></td>
        <td>
            <% if current_user.follow?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user), class:"btn btn-default", method: :delete%>
            <%elsif current_user == user%>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user), class:"btn btn-primary", method: :post%>
            <% end %>
        </td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<h1>User info</h1>
<% if @user.errors.any? %>
  <div>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li>error</li>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model:@user, local:true do |f| %>
 <diV>
  <h4>name</h4><%= f.text_field :name %>
 </diV>
<div>
 <%= f.attachment_field :profile_image %>
</div>

 <diV>
  <h4>introduction</h4><%= f.text_area :introduction %>
 </diV>




  <%= f.submit 'Update User' %>
<% end %>

app/views/users/followers.html.erb
<h1>Follower</h1>
<%= render 'users/temp', users: current_user.followers %>

app/views/users/followings.html.erb
<h1>Follow Users</h1>
<%= render 'users/temp', users: current_user.followings %>

app/views/users/index.html.erb
<div class = "container">
<div class = "row">

  <div class = "col-xs-3">
<%= render "users/list", user: @user, book: @book %>
  </div>

  <div class = "col-xs-9">
<h1>Users</h1>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan = "3"></th>
    </tr>
  </thead>
<% @users.each do |user| %>
  <tbody>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, size: "40x40", fallback: "no-image.png", class: "image" %></td>

      <td><%= link_to user.name, user_path(user.id) %></td>
      <td>
      <%#byebug%>
      <%if current_user.follow?(user)%>
        <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class:"btn btn-sm btn-success"%>
      <%elsif current_user == user%>
      <%else%>
        <%= link_to "フォローする", user_relationships_path(user), method: :post, class:"btn btn-sm btn-success"%>
      <%end%>
      </td>
      <td><%= link_to 'Show', user_path(user.id) %></td>

    </tr>

   <%end%>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class = "container">
<div class = "row">
  
  <div class = "col-xs-3">
<%= render "users/list", user: @user, book: @book %>
  </div>

  <div class = "col-xs-9">
<h1>Books</h1>
<table class = "table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
    <tr>
      
      <td><%= link_to user_path do %><%= attachment_image_tag @user, :profile_image, class: "image" , alt: "画像準備中" %><% end %></td>
   
      <td><%= link_to book.title, book_path(book.id) %></td>

      <td><%= book.body %></td>

    </tr>
  <%end%>
  </tbody>
</table>

</div>
</div>